### ISSUE TITLE
RedisGears functions raise errors after a Sentinel failover

### ISSUE THREAD

**Issue by vladcrisan13** [RedisGears/RedisGears#563]
I am using the `redislabs/redismod` Docker image in a cluster with 1 master, 2 slaves and 3 sentinels with the Bitnami image (`bitnami/redis-sentinel:latest`). 

Here's the docker-compose configuration
```
version: '2'

services:
  master:
    image: 'redislabs/redismod'
    ports:
      - '6379'

  slave:
    image: 'redislabs/redismod'
    command: >
      --slaveof master 6379
      --loadmodule /usr/lib/redis/modules/redisai.so
      --loadmodule /usr/lib/redis/modules/redisearch.so
      --loadmodule /usr/lib/redis/modules/redisgraph.so
      --loadmodule /usr/lib/redis/modules/redistimeseries.so
      --loadmodule /usr/lib/redis/modules/rejson.so
      --loadmodule /usr/lib/redis/modules/redisbloom.so
      --loadmodule /var/opt/redislabs/lib/modules/redisgears.so
      PythonHomeDir /opt/redislabs/lib/modules/python3
    depends_on:
      - master
    ports:
      - '6379'

  sentinel:
    image: 'bitnami/redis-sentinel:latest'
    depends_on:
      - master
      - slave
    environment:
      - REDIS_MASTER_HOST=master
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
    ports:
      - '26379'

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./insightdata:/db
```

After starting the containers (`docker-compose --scale slave=2 --scale sentinel=3`) and registering a RedisGears function (see the snippet below), everything works fine and the events get published into a Stream.

```from abc import ABC
from dataclasses import dataclass
from typing import Optional


@dataclass
class Test(ABC):
    event: Optional[str] = ""

    def __str__(self) -> str:
        return str(self.__dict__)


def test_it(event: dict):
    test = Test()
    execute('XADD', 'demo:debug:log', '*', 'key', F"{event['key']}:initial", 'value', str(test))
    test.event = "something else"
    execute('XADD', 'demo:debug:log', '*', 'key', F"{event['key']}:second", 'value', str(test))


gb = GearsBuilder('KeysReader')
gb.foreach(test_it)
gb.register(prefix='test:*', mode='async', eventTypes=["set"])
```

Gears execution logs:
```
1) ["{'event': 'set', 'key': 'test:before-failover', 'type': 'string', 'value': 'before'}"]
2) []
```

As soon as the master node gets stopped and the Sentinel promotes one of the slaves, the function enters a weird state - it reacts to the triggers, but it starts erroring out.

Gears execution logs:
```
["['Traceback (most recent call last):\\n', ' File \"<string>\", line 15, in test_it\\n', ' File \"<string>\", line 2, in __init__\\n', \"AttributeError: 'Test' object attribute 'event' is read-only\\n\"]\u0000"]
```

Any idea what could be the problem? I tried looking for anything related to Gears and Sentinel, potential incompatibilities or anything similar, but I didn't find anything yet.
